import type {CSSProperties,ReactNode} from 'react';
import {AbsoluteFill,Img,staticFile,useCurrentFrame,useVideoConfig,interpolate} from 'remotion';
import {theme as T,safe} from '../styles/theme';
export const Reveal=({children,delay=0,style={}}:{children:ReactNode;delay?:number;style?:CSSProperties})=>{const f=useCurrentFrame();const p=interpolate(f,[delay,delay+18],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp'});return <div style={{opacity:p,transform:`translateY(${(1-p)*24}px)`,...style}}>{children}</div>};
export const Card=({children,style={}}:{children:ReactNode;style?:CSSProperties})=><div style={{background:'white',border:`1px solid ${T.border}`,borderRadius:24,padding:30,boxShadow:'0 15px 40px #17375407',...style}}>{children}</div>;
export const Title=({children}:{children:ReactNode})=><h1 style={{fontSize:68,lineHeight:1.08,letterSpacing:-2.5,margin:'28px 0 38px',fontWeight:800}}>{children}</h1>;
export const Label=({children}:{children:ReactNode})=><div style={{fontSize:23,fontWeight:700,letterSpacing:3,color:T.blue,textTransform:'uppercase'}}>{children}</div>;
export const Demo=({text='SIMULATED VISUALS · NO EXPERIMENTAL RESULTS'}:{text?:string})=><div style={{fontSize:19,color:T.muted,letterSpacing:.7,marginTop:20,lineHeight:1.5}}>{text}</div>;
export const Shell=({children,dark=false,number}:{children:ReactNode;dark?:boolean;number:string})=>{const f=useCurrentFrame();const {durationInFrames}=useVideoConfig();const a=interpolate(f,[0,10,durationInFrames-9,durationInFrames-1],[0,1,1,0],{extrapolateLeft:'clamp',extrapolateRight:'clamp'});return <AbsoluteFill style={{background:dark?'#102b47':T.background,color:dark?'white':T.navy,fontFamily:'Inter, Arial, sans-serif'}}><AbsoluteFill style={{opacity:.45,background:dark?'radial-gradient(ellipse at 80% 20%, #3274ca44, transparent 65%)':'radial-gradient(ellipse at 80% 15%, #e4eafa, transparent 60%)'}}/><div style={{position:'absolute',left:safe.left,right:safe.right,top:safe.top,bottom:safe.bottom,opacity:a}}><div style={{display:'flex',alignItems:'center',gap:14,marginBottom:72}}><Img src={staticFile('assets/neuroai-mark.svg')} style={{width:44,height:44,filter:dark?'brightness(0) invert(1)':'none'}}/><span style={{fontSize:25,fontWeight:700,letterSpacing:2}}>NEUROAI</span><span style={{marginLeft:'auto',fontSize:20,color:dark?'#a3b8d2':T.muted}}>RESEARCH / {number}</span></div>{children}</div><div style={{display:number==='10'?'none':'block',position:'absolute',left:84,top:1580,fontSize:19,letterSpacing:2,color:dark?'#a3b8d2':T.muted}}>MOE’S RESEARCH PROJECTS · 001</div></AbsoluteFill>};
