import {useEffect,useState} from 'react';
import {Database,ExternalLink,Search} from 'lucide-react';
import {PageHeader,ScientificCard,DemoBadge,EmptyState} from '../components/ScientificCard';
import {DatasetTable} from '../components/DatasetTable';
import {datasetService} from '../services/api/datasetService';
import type {Dataset,Subject} from '../types/scientific';
export default function DataPage(){const [datasets,setDatasets]=useState<Dataset[]>([]),[subjects,setSubjects]=useState<Subject[]>([]),[search,setSearch]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(true);
 useEffect(()=>{Promise.all([datasetService.list(),datasetService.subjects('eegmmidb')]).then(([d,s])=>{setDatasets(d);setSubjects(s)}).catch(e=>setError(String(e))).finally(()=>setLoading(false))},[]);
 const dataset=datasets[0];const filtered=subjects.filter(s=>String(s.id).padStart(2,'0').includes(search.replace(/subject\s*/i,'')));
 return <><PageHeader eyebrow="DATA CATALOG" title="Dataset browser" description="Inspect the source, subject catalog, and motor imagery conditions before choosing an analysis." actions={<DemoBadge/>}/>{error&&<p className="error" role="alert">{error}</p>}{loading?<div className="skeleton"/>:dataset&&<ScientificCard title="PhysioNet EEG Motor Movement/Imagery Dataset" subtitle="Public research dataset · version 1.0.0"><div className="dataset-overview"><div className="dataset-emblem"><Database size={31}/></div><div><p>Unilateral fist imagery, bilateral hand/foot imagery, movement execution and resting baselines.</p><a className="source-link" href={dataset.source} target="_blank" rel="noreferrer">View dataset source <ExternalLink size={14}/></a></div></div><div className="metadata-grid">{[['Subjects',dataset.subjects],['Runs / subject',dataset.runs],['Sampling rate',`${dataset.samplingRate} Hz`],['EEG channels',dataset.channels]].map(([label,v])=><div key={label}><span>{label}</span><strong>{v}</strong></div>)}</div></ScientificCard>}<section id="subjects" className="page-section"><ScientificCard title="Subjects" subtitle="Illustrative local browser · trial counts and availability are demo entries" controls={<label className="table-search"><Search size={15}/><input aria-label="Search subjects" placeholder="Find a subject…" value={search} onChange={e=>setSearch(e.target.value)}/></label>}>{filtered.length?<DatasetTable subjects={filtered}/>:<EmptyState title="No matching subjects" description="Try a subject number such as 01 or clear your search."/>}</ScientificCard></section><div className="two-column"><section id="runs"><ScientificCard title="Selected imagery runs" subtitle="Unilateral left / right fist imagery"><div className="content-pad"><div className="run-cards">{[4,8,12].map((r,i)=><div key={r}><span>RUN {r}</span><strong>Motor Imagery</strong><small>Repetition {i+1} · T1 / T2</small></div>)}</div><p className="body-note">Run meaning determines event meaning. Runs 6, 10 and 14 involve both hands versus both feet and are excluded from this left/right preview.</p></div></ScientificCard></section><section id="conditions"><ScientificCard title="Condition definitions" subtitle="For runs 4, 8 and 12 only"><div className="condition-definitions"><div><i className="blue"/><strong>T1</strong><span>Imagined left fist</span></div><div><i className="purple"/><strong>T2</strong><span>Imagined right fist</span></div><div><i className="rest"/><strong>T0</strong><span>Rest · excluded from binary classification</span></div></div></ScientificCard></section></div></>}
