import {useState} from 'react';
import {FlaskConical,LoaderCircle} from 'lucide-react';
import {PageHeader,ScientificCard,EmptyState,DemoBadge} from '../components/ScientificCard';
import {Select} from '../components/Select';
import {modelNames} from '../components/ModelPredictionCard';
import {modelService} from '../services/api/modelService';
import {useResearchData} from '../hooks/useResearchData';
import type {ModelName} from '../types/scientific';
export default function ModelsPage(){const {selection}=useResearchData();const [model,setModel]=useState<ModelName>(modelNames[0]),[folds,setFolds]=useState(3),[seed,setSeed]=useState(42),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(''),[history,setHistory]=useState<string[]>([]);
 async function train(){if(!Number.isInteger(folds)||folds<2||folds>10||!Number.isInteger(seed)||seed<0||seed>4294967295){setError('Use 2–10 integer folds and a seed between 0 and 4294967295.');return}setBusy(true);setError('');try{const response=await modelService.train(model,folds,seed);setMessage(response.message);setHistory(h=>[`${new Date().toLocaleTimeString()} · ${model} · ${folds} folds · seed ${seed} · configuration preview`,...h])}catch(e){setError(String(e))}finally{setBusy(false)}}
 return <><PageHeader eyebrow="CLASSICAL EEG DECODING" title="Model training" description="Define baseline models and validation settings. Real training is deferred until the research backend is connected." actions={<DemoBadge/>}/><div className="two-column"><ScientificCard title="Baseline configuration" subtitle="Fit CSP, scaling and all learned transforms inside training folds"><form className="configuration-form" onSubmit={e=>{e.preventDefault();void train()}}><Select label="Model selection" value={model} onChange={v=>setModel(v as ModelName)}>{modelNames.map(m=><option key={m}>{m}</option>)}<option disabled>CSP + LDA — future experiment</option></Select><div className="form-grid small"><label className="form-field"><span>Cross-validation folds</span><input type="number" min="2" max="10" value={folds} required onChange={e=>setFolds(Number(e.target.value))}/></label><label className="form-field"><span>Random seed</span><input type="number" min="0" max="4294967295" required value={seed} onChange={e=>setSeed(Number(e.target.value))}/></label></div><div className="validation-note"><FlaskConical size={18}/><p>Run-aware validation should precede final evaluation. Shuffled trial splits can inflate performance through temporal dependence.</p></div><button className="button primary" disabled={busy}>{busy&&<LoaderCircle size={16} className="spin"/>}{busy?'Preparing configuration…':'Train model (demo)'}</button>{message&&<p className="status-message" role="status">{message}</p>}{error&&<p className="error" role="alert">{error}</p>}</form></ScientificCard><ScientificCard title="Model status" subtitle="No research model has been fitted"><EmptyState title="No model trained" description="Connect the Python training endpoint to run a reproducible experiment and receive validation outputs."/></ScientificCard><ScientificCard title="Performance" subtitle="Awaiting measured evaluation"><EmptyState title="No measured results" description="Demo comparisons live in Explore and Results. Measured performance will appear here after validated training."/></ScientificCard><ScientificCard title="Experiment information" subtitle="Current selection"><dl className="detail-list"><div><dt>Subject</dt><dd>Subject {String(selection.subject).padStart(2,'0')}</dd></div><div><dt>Run</dt><dd>{selection.run} · unilateral imagery</dd></div><div><dt>Input features</dt><dd>Band power / CSP (planned)</dd></div><div><dt>Positive class</dt><dd>Right hand · code 2</dd></div><div><dt>Scientific status</dt><dd>Hypotheses untested</dd></div></dl></ScientificCard></div><div className="page-section"><ScientificCard title="Training history" subtitle="Configuration previews in this browser session">{history.length?<ul className="history-list">{history.map((h,i)=><li key={i}>{h}</li>)}</ul>:<EmptyState title="No training runs" description="Preview a model configuration to inspect this workflow. No computation is performed in demo mode."/>}</ScientificCard></div></>}
