import {useState} from 'react';
import {ArrowRight,Activity,SlidersHorizontal,ScanLine,Layers,ShieldCheck,CheckCircle2,LoaderCircle} from 'lucide-react';
import {PageHeader,ScientificCard} from '../components/ScientificCard';
import {Select} from '../components/Select';
import {ResearchSelector} from '../components/ResearchSelector';
import {RawPanel,FilteredPanel} from '../features/AnalysisPanels';
import {preprocessingService} from '../services/api/preprocessingService';
import {useResearchData} from '../hooks/useResearchData';
import type {PreprocessingConfig} from '../types/scientific';
export default function PreprocessPage(){const {selection}=useResearchData();const [config,setConfig]=useState<PreprocessingConfig>({low:8,high:30,start:1,end:4,baseline:'None',artifacts:'Manual review — no automatic rejection'});const [busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('');
 const change=(key:keyof PreprocessingConfig,value:string|number)=>{setConfig({...config,[key]:value});setMessage('');setError('')};
 async function preview(){if(!Number.isFinite(config.low)||!Number.isFinite(config.high)||config.low<=0||config.high<=config.low||config.high>=80){setError('Use 0 < low frequency < high frequency < 80 Hz (Nyquist).');return;}if(!Number.isFinite(config.start)||!Number.isFinite(config.end)||config.start>=config.end){setError('Epoch start must be smaller than epoch end.');return;}if(config.baseline==='Pre-cue (−0.5 to 0 s)'&&(config.start>-.5||config.end<0)){setError('A pre-cue baseline requires an epoch containing −0.5 to 0 seconds.');return;}setBusy(true);setError('');try{const response=await preprocessingService.preview(selection,config);setMessage(response.message)}catch(e){setError(String(e))}finally{setBusy(false)}}
 return <><PageHeader eyebrow="SIGNAL PREPARATION" title="Preprocessing" description="Configure an explicit, reproducible processing strategy. Preview controls do not process EEG without a connected backend."/><ResearchSelector/><div className="workflow">{[[Activity,'Raw EEG'],[SlidersHorizontal,'Filter'],[ScanLine,'Event Extraction'],[Layers,'Epoching'],[ShieldCheck,'Artifact Handling'],[CheckCircle2,'Processed EEG']].map(([Icon,label],i)=>{const C=Icon as typeof Activity;return <div className="workflow-step" key={String(label)}><span><C size={20}/><strong>{String(label)}</strong></span>{i<5&&<ArrowRight size={16}/>}</div>})}</div><ScientificCard title="Processing configuration" subtitle="Fixed parameters should be chosen before model evaluation"><form className="configuration-form" onSubmit={e=>{e.preventDefault();void preview()}}><div className="form-grid"><label className="form-field"><span>Band-pass filter</span><input value="Zero-phase FIR · offline" readOnly/></label>{([['low','Low frequency (Hz)'],['high','High frequency (Hz)'],['start','Epoch start (seconds)'],['end','Epoch end (seconds)']] as const).map(([key,label])=><label key={key} className="form-field"><span>{label}</span><input type="number" step="0.1" required value={Number.isNaN(config[key])?'':config[key]} onChange={e=>change(key,e.target.value===''?NaN:Number(e.target.value))}/></label>)}<Select label="Baseline correction" value={config.baseline} onChange={v=>change('baseline',v)}><option>None</option><option>Pre-cue (−0.5 to 0 s)</option></Select><Select label="Artifact handling" value={config.artifacts} onChange={v=>change('artifacts',v)}><option>Manual review — no automatic rejection</option><option>Amplitude rejection (configure in backend)</option><option>ICA (future pipeline step)</option></Select></div><div className="form-footer"><p>Current charts remain fixed 8–30 Hz demo signals; changing configuration does not recompute them.</p><button className="button primary" disabled={busy}>{busy&&<LoaderCircle className="spin" size={15}/>}Preview configuration</button></div>{error&&<p className="error" role="alert">{error}</p>}{message&&<p className="status-message" role="status">{message}</p>}</form></ScientificCard><div className="two-column page-section"><RawPanel/><FilteredPanel/></div></>}
