import {useState,useEffect} from 'react';
import {ScientificCard,DemoBadge,EmptyState} from '../components/ScientificCard';
import {Select} from '../components/Select';
import {EEGTimeSeriesChart} from '../charts/EEGTimeSeriesChart';
import {FilteredEEGChart,ConditionLegend} from '../charts/FilteredEEGChart';
import {EventTimeline} from '../charts/EventTimeline';
import {EpochChart} from '../charts/EpochChart';
import {PSDChart} from '../charts/PSDChart';
import {TopographicMap,PowerScale} from '../charts/TopographicMap';
import {CSPFeatureChart} from '../charts/CSPFeatureChart';
import {useResearchData} from '../hooks/useResearchData';
import type {MotorImageryCondition} from '../types/scientific';
export function RawPanel(){const {data}=useResearchData();const [group,setGroup]=useState('all'),[view,setView]=useState('5 seconds');return <ScientificCard title="Raw EEG Signal" subtitle="Synthetic recording · 160 Hz display sampling" controls={<><Select compact label="Channels" value={group} onChange={setGroup}><option value="all">C3, Cz, C4, P3, P4</option><option value="central">C3, Cz, C4</option><option value="parietal">P3, P4</option></Select><Select compact label="View" value={view} onChange={setView}><option>5 seconds</option><option>2 seconds</option></Select></>}>{data?<EEGTimeSeriesChart data={data.raw} channels={group==='central'?['C3','Cz','C4']:group==='parietal'?['P3','P4']:['C3','Cz','C4','P3','P4']} view={view}/>:<EmptyState title="No signal loaded" description="Select a dataset and load a preview."/>}</ScientificCard>}
export function FilteredPanel(){const {data,selection}=useResearchData();const [channel,setChannel]=useState('C3');return <ScientificCard title="Filtered EEG Signal (8–30 Hz)" subtitle="Oscillatory signal preview" controls={<Select compact label="Channel" value={channel} onChange={setChannel}>{['C3','Cz','C4','P3','P4'].map(c=><option key={c}>{c}</option>)}</Select>}><ConditionLegend/>{data&&<FilteredEEGChart data={data.filtered[channel]} condition={selection.condition}/>}</ScientificCard>}
export function EventsPanel(){const {data,selection}=useResearchData();const [condition,setCondition]=useState<MotorImageryCondition>('left');useEffect(()=>{if(selection.condition!=='left-right')setCondition(selection.condition)},[selection.condition]);return <ScientificCard title="Event Markers & Epochs" subtitle="Cue-aligned visualization preview"><ConditionLegend/>{data&&<EventTimeline events={data.events} condition={selection.condition}/>}<div className="epoch-heading"><h3>Epoch Examples</h3><div className="segmented">{(['left','right'] as const).map(c=><button key={c} aria-pressed={condition===c} disabled={selection.condition!=='left-right'&&selection.condition!==c} className={condition===c?`active ${c}`:''} onClick={()=>setCondition(c)}>{c==='left'?'Left':'Right'} Hand (MI)</button>)}</div></div>{data&&<EpochChart data={data.epochs[condition]} condition={condition}/>}<p className="card-footnote">Display window −1 to +1 s; backend analysis epochs remain 1–4 s.</p></ScientificCard>}
export function PSDPanel(){const {data,selection}=useResearchData();return <ScientificCard title="Power Spectral Density (PSD)" subtitle="Welch-style illustrative spectra"><ConditionLegend/>{data&&<PSDChart data={data.psd} condition={selection.condition}/>}<div className="band-key"><span>Alpha / Mu · 8–12 Hz</span><span>Beta · 13–30 Hz</span></div></ScientificCard>}
export function TopographyPanel(){const {data,selection}=useResearchData();const [band,setBand]=useState('mu'),[view,setView]=useState('both');useEffect(()=>{setView(selection.condition==='left-right'?'both':selection.condition)},[selection.condition]);return <ScientificCard title="Topographic Brain Maps" subtitle="Scalp band-power illustration · not source localization" controls={<><Select compact label="Condition" value={view} onChange={setView}><option value="both">Left vs Right (MI)</option><option value="left">Left Hand (MI)</option><option value="right">Right Hand (MI)</option></Select><Select compact label="Frequency" value={band} onChange={setBand}><option value="mu">Mu Band (8–12 Hz)</option><option value="beta">Beta Band (13–30 Hz)</option></Select></>}><div className="topography-row">{data&&(['left','right'] as const).filter(c=>(view==='both'||view===c)&&(selection.condition==='left-right'||selection.condition===c)).map(c=><TopographicMap key={c} points={data.topography} condition={c} band={band}/>)}</div><PowerScale/></ScientificCard>}
export function CSPPanel(){const {data}=useResearchData();const [component,setComponent]=useState(1);return <ScientificCard title="Feature Importance (CSP)" subtitle="Pattern weights · not validated predictive importance" help="CSP patterns and classifier feature importance are different. These demo weights do not establish regional contribution." controls={<Select compact label="Component" value={component} onChange={v=>setComponent(Number(v))}>{[1,2,3,4].map(n=><option key={n} value={n}>CSP Pattern {n}</option>)}</Select>}>{data&&<CSPFeatureChart data={data.csp} component={component}/>}</ScientificCard>}
export function AnalysisLoading(){return <div className="loading-grid" role="status" aria-label="Loading scientific preview">{[1,2,3,4].map(n=><div className="skeleton" key={n}/>)}<span className="sr-only">Loading data…</span></div>}
